//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCanteenServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponNotification
    {
        public long CN_ID { get; set; }
        public long CN_CM_ID { get; set; }
        public string CN_CM_Empid { get; set; }
        public System.DateTime CN_CM_Date { get; set; }
        public int CN_CM_FLR_ID { get; set; }
        public bool CN_CM_Requested_bln { get; set; }
        public bool CN_CM_Accepted_bln { get; set; }
    }
}
