//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCanteenServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyMenuMaster
    {
        public int DMM_ID { get; set; }
        public Nullable<int> DMM_WDM_ID { get; set; }
        public Nullable<int> DMM_MI_ID { get; set; }
        public Nullable<int> DMM_MI_FCM_ID { get; set; }
        public Nullable<int> DMM_FM_ID { get; set; }
        public Nullable<System.DateTime> DMM_From_Date { get; set; }
        public Nullable<System.DateTime> DMM_To_Date { get; set; }
        public System.DateTime Todays_Date { get; set; }
    }
}
