//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCanteenServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Empid { get; set; }
        public string EmpFirstName { get; set; }
        public string EmpLastName { get; set; }
        public Nullable<long> EmpMobNo { get; set; }
        public string EmpLoginId { get; set; }
        public string EmpPassword { get; set; }
        public Nullable<int> EmpType { get; set; }
        public Nullable<int> Emp_FM_ID { get; set; }
    }
}
