//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCanteenServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Floor_Master
    {
        public int FM_Id { get; set; }
        public string FM_Description { get; set; }
    }
}
