//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCanteenServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodOrderMaster
    {
        public long FOM_ID { get; set; }
        public string FOM_EmpLoginId { get; set; }
        public int FOM_FloorId { get; set; }
        public int FOM_CategoryId { get; set; }
        public int FOM_MenuItemId { get; set; }
        public int FOM_Qty { get; set; }
        public Nullable<long> FOM_OrderNumber { get; set; }
        public double FOM_OrderCost { get; set; }
        public System.DateTime FOM_Date { get; set; }
        public bool FOM_ToCart { get; set; }
        public bool FOM_RequestedBln { get; set; }
        public bool FOM_ConfirmedBln { get; set; }
        public bool FOM_CancelledBln { get; set; }
    }
}
