//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCanteenServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem_Master
    {
        public int MI_ID { get; set; }
        public string MI_Description { get; set; }
        public Nullable<double> MI_Price { get; set; }
        public Nullable<int> MI_FCM_ID { get; set; }
        public int MI_FoodType { get; set; }
    }
}
